models/alert.py
import uuid
from dataclasses import dataclass, field
from typing import Dict, List
from models.item import Item
from common.database import Database
from models.model import Model
from models.user import User
from libs import Mailgun


@dataclass(eq=False)  # remove all equality generation you can't compare two alerts
class Alert(Model):
    name: str
    item_id: str
    price_limit: float
    user_email: str
    _id: str = field(default_factory=lambda: uuid.uuid4().hex)
    collection: str = field(init=False, default="alerts")

    def __post_init__(self):
        self.item = Item.get_element_by_id(self.item_id)
        self.user = User.find_by_email(self.user_email)

    def json(self) -> Dict:
        return {
            "name": self.name,
            "_id": self._id,
            "price_limit": self.price_limit,
            "item_id": self.item_id,
            "user_email": self.user_email
        }

    def load_item_price(self) -> float:
        self.item.load_price()
        return self.item.price

    def notify_if_price_reached(self):
        if self.item.price < self.price_limit:
            print(f"Item {self.item} has reached a price below {self.price_limit}. Latest price {self.item.price}.")
            
            Mailgun.send_mail(
                [self.user_email],
                f'Notification for {self.name}',
                f'Your alert {self.name} has reached a price under {self.price_limit}. The latest price is : {self.item.price}. \n Go to this address to check your item : {self.item.url}.',
                f'<p> Your alert {self.name} has reached a price under {self.price_limit}.</p><p>The latest price is {self.item.price}.</p><p> Click <a href="{self.item.url}"> here </a> to purchase your item </p>'
            )

views/alerts.py
import json

from flask import Blueprint, render_template, request, redirect, url_for, session
from models.alert import Alert
from models.store import Store
from models.item import Item
from models.user import requires_login



alerts_blueprint = Blueprint("alerts", __name__)


@alerts_blueprint.route("/")
@requires_login
def index():
    alerts = Alert.find_many_by('user_email', session['email'])
    return render_template("alerts/index.html", alerts=alerts)


@alerts_blueprint.route("/new", methods=["GET", "POST"])
@requires_login
def new_alert():
    if request.method == 'POST':
        alert_name = request.form["alert_name"]
        item_url = request.form['item_url']
        price_limit = request.form["price_limit"]

        store = Store.get_by_url(item_url)  # What if this store is not database
        item = Item(item_url, store.tag_name, store.query)
        item.load_price()
        item.save_to_database()
        alert = Alert(alert_name, item._id, float(price_limit), session["email"])
        alert.save_to_database()

    return render_template("alerts/new_alert.html")


@alerts_blueprint.route("/edit/<string:alert_id>", methods=['GET', 'POST'])
@requires_login
def edit_alert(alert_id):
    alert = Alert.get_element_by_id(alert_id)

    if request.method == "POST":
        price_limit = float(request.form['price_limit'])
        alert.price_limit = price_limit
        alert.save_to_database()

        return redirect(url_for('.index'))  # this changes to the index endpoint defined within this blueprint the dot means within the current blueprint

    return render_template('alerts/edit_alert.html', alert=alert)


@alerts_blueprint.route("/delete/<string:alert_id>", methods=['GET', 'POST'])
@requires_login
def delete_alert(alert_id):
    alert = Alert.get_element_by_id(alert_id)
    if alert.user_email == session['email']:
        alert.remove_from_database()

    return redirect(url_for(".index"))

templates/alerts/edit_alert.html
{% extends "base.html" %}
{% block content %}
<header>
    <h1>Update Alert</h1>
</header>
<section class="update-alert-form">
    <form method="post">
        <div class="form-group">
            <label for="alert_name"> Alert Name</label>
            <input type="text" class="form-control" id="alert_name" name="alert_name" value="{{alert.name}}" disabled>
        </div>
        <div class="form-group">
            <label for="item_url">Item URL</label>
            <input type="text" class="form-control" id="item_url" name="item_url"
                value="{{alert.item.url}}" disabled>

        </div>
        <div class="form-group">
            <label for="price_limit">Price limit</label>
            <input type="text" class="form-control" id="price_limit" name="price_limit" placeholder="1000"
                aria-describedby="priceLimiHelp" value="{{alert.price_limit}}">
            <small id="priceLimitHelp" class="form-text text-muted">
                What is the price your product has to reach for you to be notified

            </small>
        </div>
        <button type="submit" class="btn btn-primary">Update</button>

    </form>
</section>
{% endblock %}

templates/alerts/index.html
{% extends "base.html" %}
{% block content %}

<header>
    <h1> Alerts </h1>

</header>
<section>
    <div class="list-group mb-3">
        {% for alert in alerts %}
        <div class="list-group-item">
            <h4>{{alert.name}}</h4>
            <p>
                <a href="{{alert.item.url}}">{{alert.item_id}} (€ {{alert.item.price}})</a>
            </p>
            <a class="btn btn-secondary" href="{{url_for('alerts.edit_alert', alert_id=alert._id)}}">Edit</a>
            <a class="btn btn-danger" href="{{url_for('alerts.delete_alert', alert_id = alert._id)}}">Remove</a>
        </div>
        {% endfor %}
    </div>
    <a class="btn btn-primary" href="{{ url_for('alerts.new_alert')}}">
        New Alert
    </a>
</section>
{% endblock %}

templates/alerts/new_alert.html
{% extends "base.html" %}
{% block content %}
<header>
    <h1>Create Alert</h1>
</header>
<section class="create-alert-form">
    <form method="post">
        <div class="form-group">
            <label for="alert_name"> Alert Name</label>
            <input type="text" class="form-control" id="alert_name" name="alert_name" placeholder="Ipad 10 inches">
        </div>
        <div class="form-group">
            <label for="item_url">Item URL</label>
            <input type="text" class="form-control" id="item_url" name="item_url"
                placeholder="https://www.fnac.pt/macpro/12inc....">

        </div>
        <div class="form-group">
            <label for="price_limit">Price limit</label>
            <input type="text" class="form-control" id="price_limit" name="price_limit" placeholder="1000"
                aria-describedby="priceLimiHelp">
            <small id="priceLimitHelp" class="form-text text-muted">
                What is the price your product has to reach for you to be notified

            </small>
        </div>
        <button type="submit" class="btn btn-primary">Create</button>

    </form>
</section>
{% endblock %}