models/store.py
from typing import Dict
import uuid
import re
from dataclasses import dataclass, Field, field
from models.model import Model

@dataclass(eq=False)
class Store(Model):
    name: str
    url_prefix: str # https://www.johnlewis.com/ or https://www.fnac.pt
    tag_name: str
    query: Dict
    _id: str = field(default_factory=lambda: uuid.uuid4().hex)
    collection: str = field(init=False, default="stores")

    def json(self):
        return {
            "_id": self._id,
            "name": self.name,
            "url_prefix": self.url_prefix,
            "tag_name": self.tag_name,
            "query": self.query,
        }

    @classmethod
    def get_by_name(cls, store_name: str) -> "Store":
        return cls.find_one_by("name", store_name)

    @classmethod
    def get_by_url_prefix(cls, url_prefix: str) -> "Store":
        url_regex = {"$regex": "^{}".format(url_prefix)}
        # the $ regex is a command within mongo db it is called regular expression validation
        # ^means start with {url_prefix}
        # This will mean that if the argument given to the function is www.fnac.pt
        # And in the database there is only a register for www.fnac.pt/items
        # mongodb will still find a match
        return cls.find_one_by("url_prefix", url_regex)

    @classmethod
    def get_by_url(cls, url: str) -> "Store":
        """
        Return a store from a url like "https://www.fnac.pt./ipad/sdfsdf.html
        Arguments: 
        url -> The item's url
        """
        pattern = re.compile(r"(https?://.*?/)")
        match = pattern.search(url)
        url_prefix = match.group(1)
        return cls.get_by_url_prefix(url_prefix)

views/stores.py
from flask import Blueprint, render_template, request, redirect, url_for
from models.store import Store
from models.user.decorators import requires_admin
import json

store_blueprint = Blueprint("stores", __name__)


@store_blueprint.route("/")
def index():
    stores = Store.all()
    return render_template("/stores/index.html", stores=stores)


@store_blueprint.route("/new_store", methods=['GET', 'POST'])
@requires_admin
def new_store():

    if request.method == "POST":
        name = request.form["store_name"]
        tag_name = request.form["tag_name"]
        url_prefix = request.form["store_url"]
        query = json.loads(request.form["query"])
        Store(name, url_prefix, tag_name, query).save_to_database()

    return render_template("/stores/new_store.html")


@store_blueprint.route("/delete/<string:store_id>", methods=["GET", "POST"])
@requires_admin
def delete_store(store_id):
    store = Store.get_element_by_id(store_id)
    store.remove_from_database()

    return redirect(url_for(".index"))

templates/stores/index.html
{% extends "base.html" %}
{% block content %}

<header>
    <h1> Alerts </h1>

</header>
<section>
    <div class="list-group mb-3">
        {% for store in stores %}
        <div class="list-group-item">
            <h4>{{store.name}}</h4>
            <p>
                <a href="{{store.url_prefix}}">Website</a>
            </p>

            {% if session['email'] == config.ADMIN %}

            <a class="btn btn-danger" href="{{url_for('stores.delete_store', store_id=store._id)}}">
                Delete
            </a>
            {% endif %}

        </div>
        {% endfor %}
    </div>
    {% if session['email'] == config.ADMIN %}
    <a class="btn btn-primary" href="{{ url_for('stores.new_store')}}">
        New Store
    </a>
    {% endif %}
</section>
{% endblock %}

templates/stores/new_store.html
{% extends "base.html" %}
{% block content %}

<header>
        <h1>Create Store</h1>
    </header>
    <section class="create-store-form">
        <form method="post">
            <div class="form-group">
                <label for="store_name"> Store Name</label>
                <input type="text" class="form-control" id="store_name" name="store_name" placeholder="Fnac">
            </div>
            <div class="form-group">
                <label for="store_url">Store URL</label>
                <input type="text" class="form-control" id="store_url" name="store_url"
                    placeholder="https://www.fnac.pt">
    
            </div>
            <div class="form-group">
                <label for="tag_name">Tag name</label>
                <input type="text" class="form-control" id="tag_name" name="tag_name" placeholder= "span"
                    aria-describedby="tag_nameHelp">
                <small id="tag_nameHelp" class="form-text text-muted">
                    what is the html tag where the price information is stored within
    
                </small>
            
            </div>

            <div class="form-group">
                    <label for="query">Tag name</label>
                    <input type="text" class="form-control" id="query" name="query" placeholder= "{'class': 'price'}"
                        aria-describedby="queryHelp">
                    <small id="queryHelp" class="form-text text-muted">
                        what is the query for the price of an item within this store
        
                    </small>
                
                </div>
            <button type="submit" class="btn btn-primary">Create</button>
    
        </form>
    </section>

{% endblock %}